piro14/urls.py
from .import views
from django.contrib import admin
from django.urls import path, re_path, register_converter, include
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'piro14'

urlpatterns = [
    path('', views.main_before, name='main_before'), #로그인 전 메인화면
    path('login/', views.main_after, name='main_after'), #로그인 후 메인화면
    path('google/', TemplateView.as_view(template_name='piro14/index.html'), name='googlelogin'), #?
    path('accounts/', include('allauth.urls')), #?
    path('list/', views.game_list, name='game_list'), #게임 list
    path('detail/<int:pk>/', views.game_detail, name='game_detail'), #게임 디테일
    path('attack/', views.game_attack, name='game_attack'), #공격하기
    path('ranking/', views.game_ranking, name='game_ranking'), #랭킹보기
    path('delete/<int:pk>/', view=views.game_delete, name = 'game_delete'),
    path('logout/', auth_views.LogoutView.as_view(template_name='piro14/main_bflog.html'), name='logout'),
    path('counterattack/<int:pk>/', views.game_counter_attack, name='game_counter_attack'), #반격하기
]

pirolast/urls.py
from django.contrib import admin
from django.urls import path, re_path, register_converter, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('main/', include('piro14.urls')),
]

piro14/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
import datetime
from django.contrib.auth.models import UserManager as DefaultUserManager, User
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser

from django.db.models.signals import post_save
from django.dispatch import receiver


# class newUser(AbstractBaseUser):
#     name = models.CharField(max_length=50, verbose_name="이름", default = "user27")
#     password = models.CharField(max_length=50, default='123')
#     score = models.IntegerField(default=0)
#     USERNAME_FIELD = 'name'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()



class UserManager(DefaultUserManager):
    def get_or_create_google_user(self, user_pk, extra_data):
        user = User.objects.get(pk=user_pk)
        user.username = extra_data['name']
        user.save()
        return user


class Game(models.Model):
    creator = models.ForeignKey(User, related_name="Host", on_delete=models.DO_NOTHING) # 방
    opponent = models.ForeignKey(User, related_name="Participant", null=True, blank=True, on_delete=models.DO_NOTHING)#참가자
    winner = models.ForeignKey(User, related_name='Win', null=True, blank=True, on_delete=models.DO_NOTHING) # 우승자
    loser = models.ForeignKey(User, related_name="Lose", null=True, blank=True, on_delete=models.DO_NOTHING)
    current_turn = models.ForeignKey(User, related_name='Turn', on_delete=models.DO_NOTHING) # 현재

    creator_card = models.IntegerField(verbose_name = "creator_card", null=True, blank=True)
    opponent_card = models.IntegerField(verbose_name="opponent_card", null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True) # 방 생성
    draw = models.BooleanField(default=False)
    greater = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    def __unicode__(self):
        return 'Game #{0}'.format(self.pk)

piro14/forms.py
from django import forms
from .models import *


class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        # fields='__all__'
        fields = ['creator','creator_card', 'opponent']
        

piro14/views.py
from allauth.socialaccount.adapter import DefaultSocialAccountAdapter
from django.contrib.auth.models import User
from .models import *
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
import random
from django.db.models.query import Q
from .forms import GameForm

class SocialAccountAdapter(DefaultSocialAccountAdapter):
    def save_user(self, request, sociallogin, form=None):
        user = super(SocialAccountAdapter, self).save_user(request, sociallogin, form)

        social_app_name = sociallogin.account.provider.upper()

        if social_app_name == "GOOGLE":
            User.objects.get_or_create_google_user(user_pk=user.pk, user_email=user.email, user_name=user.name)

#(1번)
def main_before(request):
    user = User.objects.all()

    return render(request, 'piro14/main_bflog.html', {
        'user': user,
    })

#(2번)
def main_after(request):
    user = User.objects.all()
    return render(request, 'piro14/main_aflog.html', {
        'user': user,
    })
#메인 완성쪽


# 게임 목록(4번)
def game_list(request):
    user=request.user
    games = Game.objects.filter(Q(creator=user)|Q(opponent=user))
    ctx = {
           'games' : games
           }
    return render(request,'piro14/game_list.html', ctx) # 리스트 템플릿 경로와 매핑
    
# 게임 삭제
def game_delete(request, pk):
    game = get_object_or_404(Game, pk=pk)
    if request.method == 'POST':
        game.delete()
        return redirect('piro14:game_list.html') # 게임 리스트로 이동
    else:
        return redirect('piro14:game_list.html') # 게임 리스트로 이동

# 세부내역(5번)
def game_detail(request, pk):
    user = request.user
    game = Game.objects.get(id=pk)
    ctx = {
        'game':game,
        'user':user,
    }
    return render(request, 'piro14/game_detail.html', ctx ) #세부내역 템플릿 경로 매핑

# 랭킹(7번)
def game_ranking(request):
    users = User.objects.all().order_by('-score') #유저매니저 클래스에 score 객체 추가할 시 
    ctx = {
        'users':users,
    }
    return render(request, 'piro14/game_ranking.html', ctx )#랭킹 템플릿 경로 매핑


#공격(3번)
#장고 폼버전
# def game_attack(request):
#     if request.method == "POST": #post방식
#         # form = GameForm(request.POST)
#         # if form.is_valid():
#         data = request.POST
#         creator = request.user
#         opponent = User.objects.get(username=data.get('opponent')
#         creator_card = int(data.get('creator_card'))
#         current_turn = opponent

#         game = Game()
#         game.creator = creator
#         game.opponent = opponent
#         game.creator_card = creator_card
#         game.current_turn = current_turn
#         game.save()

#         return redirect('piro14/game_detail.html', pk=game.id) # 공격 템플릿 매핑
#     else:
#         form = GameForm() #get방식
#         ctx={"form": form}
#         return render(request, "piro14/game_form.html", ctx)

def game_attack(request):
    if request.method == 'POST': # POST 형식으로 폼에 입력받은 값을 서버에 요청할 경우
        data = request.POST
        creator = request.user
        opponent = User.objects.get(username=data.get('opponent'))
        creator_card = int(data.get('creator_card'))
        current_turn = opponent

        game = Game()
        game.creator = creator
        game.opponent = opponent
        game.creator_card = creator_card
        game.current_turn = current_turn
        game.greater = random.choice([True, False])
        game.save()

        return redirect('piro14:game_detail', pk=game.id)

    else:
        creator = request.user
        opponent_options = User.objects.exclude(id=creator.id) #pk를 제외한 나머지
        creator_card_options = random.sample(range(1,11), 5)#1~10의 정수중 5개 뽑아서 리스트 생성
        # 클래스의 객체들을 넣고
        ctx = {
            'creator' : creator,
            'opponent_options' : opponent_options,
            'creator_card_options' : creator_card_options
        }
        return render(request, 'piro14/game_attack.html', ctx )
    # 각각의 객체들을 ctx에 넣고
    # 공격 템플릿과 매핑함

#반격(6번) - 구현 필요
def game_counter_attack(request, pk):
    if request.method == 'POST': # POST 형식으로 폼에 입력받은 값을 서버에 요청할 경우
        game = Game.objects.get(id=pk)
        data = request.POST
        game.opponent_card = int(data.get('opponent_card'))
        game.current_turn = game.creator
        

        game_creator = Profile.objects.get(user=game.creator)
        game_opponent = Profile.objects.get(user=game.opponent)

        if game.greater == True and game.creator_card > game.opponent_card:
            game.winner = game.creator
            game.loser = game.opponent
            game_creator.score += game.creator_card
            game_opponent.score -= game.opponent_card
        elif game.greater == True and game.creator_card < game.opponent_card: 
            game.winner = game.opponent
            game.loser = game.creator
            game_creator.score -= game.creator_card
            game_opponent.score += game.opponent_card
        elif game.greater == False and game.creator_card > game.opponent_card:
            game.winner = game.opponent
            game.loser = game.creator
            game_creator.score -= game.creator_card
            game_opponent.score += game.opponent_card
        elif game.greater == False and game.creator_card < game.opponent_card: 
            game.winner = game.creator
            game.loser = game.opponent
            game_creator.score += game.creator_card
            game_opponent.score -= game.opponent_card
        else: 
            game.draw = True
            game_creator.score += game.creator_card
            game_opponent.score += game.opponent_card
            
        game.completed = True
        return redirect('piro14:game_detail', pk=game.id)
    
    else:
        game = Game.objects.get(id=pk)
        creator = game.creator
        opponent_card_options = random.sample(range(1,11), 5)#1~10의 정수중 5개 뽑아서 리스트 생성
        # 클래스의 객체들을 넣고
        ctx = {
            'opponent_card_options' : opponent_card_options,
            'creator' : creator
        }
        return render(request, 'piro14/game_counter_attack.html', ctx )

piro14/templates/piro14/game_attack.html
{% extends "piro14/layout.html" %}

{% block content %}


<form action="" method="post" autocomplete="off">
    {% csrf_token %}
    <table class="table">
        <tbody>
            <tr>
                <th>내가 고른 카드</th>
                <td>
                    <select name="creator_card">
                        {% for card_option in creator_card_options %}
                            <option value = "{{ card_option }}"> {{ card_option }} </option>
                        {% endfor %}
                    </select>
                </td>
            </tr>

            <tr>
                <th>공격할 상대는?</th>
                <td>
                    <select name="opponent">
                        {% for opponent_option in opponent_options %}
                            <option> {{ opponent_option }} </option>
                        {% endfor %}
                    </select>
                </td>
            </tr>

        </tbody>
    </table>
    <input type="submit" value="공격하기!" class="btn btn-primary" />
</form>
{% endblock %}

piro14/templates/piro14/game_counter_attack.html
{% extends "piro14/layout.html" %}

{% block content %}
<h1> {{ creator }} 에게 반격하세요! </h1>

<form action="" method="post" autocomplete="off">
    {% csrf_token %}
    <table class="table">
        <tbody>
            <tr>
                <th>내가 고른 카드</th>
                <td>
                    <select name="opponent_card">
                        {% for card_option in opponent_card_options %}
                            <option value = "{{ card_option }}"> {{ card_option }} </option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
        </tbody>
    </table>
    <input type="submit" value="반격하기!" class="btn btn-primary" />
</form>
{% endblock %}

piro14/templates/piro14/game_detail.html
{% extends "piro14/layout.html" %}

{% block content %}
    {% if user == game.creator and game.completed != True %}
        <h2>{{ game.id }} - {{ game.creator }} vs {{ game.opponent }}</h2>
        
        <br/><br/>
        <h3>진행중...</h3>
        <h3>{{ user.username }}: {{ game.creator_card }}</h3>

        <form action = "{% url 'piro14:game_delete' game.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value = '게임 취소'>
        </form>

        <button><a href="{% url 'piro14:game_list'%} " >전적 목록</a></button>
    {% endif %}


    {% if user == game.opponent and game.current_turn == user %}
        <h2>{{ game.id }} - {{ game.creator }} vs {{ game.opponent }}</h2>
        
        <br/><br/>
        <button><a href="{% url 'piro14:game_counter_attack' game.id %} " >대응하기</a></button>

        <hr/>
        <br/><br/>
        <button><a href="{% url 'piro14:game_list' %} " >전적 목록</a></button>

    {% endif %}


    {% if game.completed %}
        <h2>{{ game.id }} - {{ game.creator }} vs {{ game.opponent }}</h2>
        <hr/>
        
        {% if game.greater == True %}    
            <h2>숫자가 더 큰 사람이 대결에서 이깁니다</h2>
        {% else %}
            <h2>숫자가 더 작은 사람이 대결에서 이깁니다</h2>
        {% endif %}

        <hr/>
        <h3>{{ game.creator.username }} : {{ game.creator_card }}</h3>
        <h3>{{ game.opponent.username }} : {{ game.opponent_card }}</h3>
        <hr/>

        {% if game.draw == True %}
        <h3>결과:비김</h3>
        <hr/>
        <h3>점수: + {{ game.creator_card }}</h3>

        {% elif user == game.winner %}
        <h3>결과:승리</h3>
        <hr/>
            {% if game.creator == user %}
                <h3>점수: + {{ game.creator_card }}</h3>
            {% else %}
                <h3>점수: + {{ game.opponent_card }}</h3>
            {% endif %}

        {% else %}
        <h3>결과:패배</h3>
        <hr/>
            {% if game.creator == user %}
                <h3>점수: - {{ game.creator_card }}</h3>
            {% else %}
                <h3>점수: - {{ game.opponent_card }}</h3>
            {% endif %}

        {% endif %}
    {% endif %}



{% endblock %}

piro14/templates/piro14/game_list.html
{% extends "piro14/layout.html" %}

{% block content %}
<div>
현재 플레이어의 게임 전적을 보여주는 페이지입니다. 글을 조금 더 써봅시다. 조금만 더요.
<br/>진행 중인 게임은 취소할 수 있어요! 물론 자신이 공격한(=도전장을 내민)게임만 해당됩니다.

</div>
<p>현재 플레이어: {{ user.username }}</p>
<div id = "game_list">
    {% for game in games %}
            <div>
                <span>{{ game.id }} - {{ game.creator }} vs {{ game.opponent }}</span>
                {% if user == game.winner %}
                    <span>
                            결과: 승리
                    </span>
                {% elif user == game.creator and game.current_turn != user %}
                    <span>
                        진행중...
                        <form action = "{% url 'piro14:game_delete' game.id %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value = '게임 취소'>
                        </form>
                    </span>
                {% elif user == game.opponent and game.current_turn == user %}
                    <span>
                        <button><a href="{% url 'piro14:game_counter_attack' game.id%} " >반격하기</a></button>
                    </span>
                {%elif user == game.loser %}
                    <span>
                            결과: 패배
                    </span>
                {% endif %}
                <span>
                    <button><a href="{% url 'piro14:game_detail' game.id %}" >게임 정보</a></button>
                </span>
            </div>
    {% endfor %}
</div>
{% endblock %}

piro14/templates/piro14/game_ranking.html
##game ranking

{% extends "piro14/layout.html" %}

{% block content %}
<h1>PiRO 명예의 전당</h1>

{%for rank in users %}
    <p>{{forloop.counter}}등 {{users.name}}님! 총점수:{{users.score}}점</p>
    <button><a href = "{%url 'piro14:game_list' %}">전적 목록</a></button>
{% endfor %}


{% endblock %}

piro14/templates/piro14/index.html
{% load socialaccount %}
{% providers_media_js %}


<html>
    <head>
        <title>Google Registration</title>
    </head>
    <body>

<a href="{% provider_login_url "google" %}">로그인</a>

{% for account in user.socialaccount_set.all %}

<p>email: {{ account.extra_data.email }}</p>
<p>Name: {{ account.extra_data.name }}</p>
{% endfor %}
py

    </body>
</html>

piro14/templates/piro14/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Piro CardGame</title>
    <style>
        * {
            text-decoration: none;
            list-style-type: none;
        }

        body {
            background: lavender;
        }

        #content {
            background: lightblue;
            margin: 0 auto;
            width: 100%;
            height: 600px;
            text-align: center;
        }
        
        #top_nav {
            display:flex;
            justify-content: center;

        }
        #top_nav ul a {
            display: inline-block;
            margin: 0 50px;
            color: white;
            font-size: 15pt;
        }
        
        .last {
            text-align: center;
        }

    </style>

    {% block head %}
    {% endblock %}

</head>
<body>
    
    <nav id='top_nav'>
        <ul>
            <a href="{% url 'piro14:main_after' %}">PIROGRAMING CARDGAME</a>
            <a href="{% url 'piro14:game_attack' %}">게임하기</a>
            <a href="">랭크보기</a>   
            <a href="{% url "piro14:logout" %}">로그아웃</a> 
        </ul>
    </nav>
    
    <div id="content">

        <div id="content__top">
            <h2 class="title">
                {% block title %}
                {% endblock %}
            </h2>
            <p class="detail">
                {% block detail %}
                {% endblock %}
            </p>
        </div>
    

        <hr/>

        {% block content %}
        {% endblock %}    

    </div>

    <hr/>
    <footer class="last">
        <div>피로그래밍 14기 화이티이이잉</div>
        <div>방구석 피로그래밍 연구소 | 다들 마지막까지 빠이팅입니다앙</div>

</body>
</html>

piro14/templates/piro14/main_aflog.html
{% extends "piro14/layout.html" %}

{% block content %}

<div class="main_title">

    <h1>전 세계 피로그래머와</h1>
    <h1>한 판 승부 숫자카드게임</h1>

</div>

<p>{{ user.username }}님이 로그인 중</p>

<button class="gameplay">
<a href="{% url 'piro14:game_attack' %}">게임하기<a>
<br/>
<a href="{% url 'piro14:game_list' %}">전적보기</a>
</button>

{% endblock %}  

piro14/templates/piro14/main_bflog.html
{% load socialaccount %}
{% providers_media_js %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Piro CardGame</title>
    <style>
        * {
            text-decoration: none;
            list-style-type: none;
        }

        body {
            background: lavender;
        }

        #content {
            background: lightblue;
            margin: 0 auto;
            width: 100%;
            height: 600px;
            text-align: center;
        }
        
        #top_nav {
            display:flex;
            justify-content: center;

        }
        #top_nav ul a {
            display: inline-block;
            margin: 0 50px;
            color: white;
            font-size: 15pt;
        }
        
        .last {
            text-align: center;
        }

    </style>

    {% block head %}
    {% endblock %}

</head>
<body>
    
    <nav id='top_nav'>
        <ul>
            <a href="">PIROGRAMING CARDGAME</a>
            <a href="{% provider_login_url "google" %}">로그인</a>
        </ul>
    </nav>
    
    <div id="content">

        <div id="content__top">
            <h2 class="title">
                {% block title %}
                {% endblock %}
            </h2>
            <p class="detail">
                {% block detail %}
                {% endblock %}
            </p>
        </div>
    

        <hr/>
{% block content %}

<div class="main_title">

    <h1>전 세계 피로그래머와</h1>
    <h1>한 판 승부 숫자카드게임</h1>

</div>

<button class="gameplay">
<a href="">게임하기<a> 
</button>

{% endblock %}  

    </div>

    <hr/>
    <footer class="last">
        <div>피로그래밍 14기 화이티이이잉</div>
        <div>방구석 피로그래밍 연구소 | 다들 마지막까지 빠이팅입니다앙</div>

</body>
</html>